reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
osx_image: xcode7.3
before_install: true
install: true
script:
- script/cibuild
branches:
  only:
  - master
notifications:
  slack:
    secure: UIG9+o5gRYZGpRRBIB/9nFBoXvSOI3Ll63KuUMd/u/CvFpByLY0MSX5LY18v6hYqA3UNjEhOO9x1j91H7JOjbI0NYtq/7+qehUDWORaQc+NSUozKLmkIGm1M6RYayUw61J9fYpyt8AjpbGIb78i7T8ckz7dYkyhEJcGz7L+30pw=
env:
  matrix:
    - SCHEME="JWTDecode-iOS" IOS_DESTINATION_VERSION="9.1" CARTHAGE_BUILD_PLATFORM="iOS"
    - SCHEME="JWTDecode-iOS" IOS_DESTINATION_VERSION="9.0" CARTHAGE_BUILD_PLATFORM="iOS"
    - SCHEME="JWTDecode-iOS" IOS_DESTINATION_VERSION="8.4" CARTHAGE_BUILD_PLATFORM="iOS"
    - SCHEME="JWTDecode-OSX" CARTHAGE_BUILD_PLATFORM="Mac"
  global:
  - secure: hHc0uhSg57mTBfFUX7ZwZe85IlLMS+mMgOx192fnVyeD81S2AFxaO4nWRpXHktkR68HwDsYJ4emVeoaLxZb8tkkej+nf1L3NIY3FFEJpIEAmrYMv9AoFb0ZtT1IwGOt92bll0DqzZotOVOrPVZeS8MspwZAFqXHAgBszfJut/2w=
  - secure: dYWR8CvhN1g1ta3+ARWO5wYUIhhA5BjTKE29Df+URdNVuJMvvtNwuE8YpI9yKKz/rp9PbKo+6jAMozbiokj2Baf8xOawQvyiRWA7c5YRslM2oNuVX33yl949JMzpJmKRJiFi59lbu8gAmI090cHiG9HVw7etpNMy3JGCx9GIJhc=
